import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Card from '../components/Card'
import CardInterface from '../components/CardInteface'
import styles from '../styles/Home.module.css'

const defaultData = [{
  time: 11,
  type: 'days'
},{
  time: 8,
  type: 'hours'
},{
  time: 11,
  type: 'minutes'
},{
  time: 11,
  type: 'seconds'
}]


const Home: NextPage<CardInterface[]> = () => {

  const [remainingTime, setRemainingTime] = useState(defaultData);

  const updateRemainingTime = ()=>{
      const minute = 1000 * 60;
      const hour = minute * 60;
      const day = hour * 24;
      const now = Date.now();
      const reminderDate = new Date("07/01/2022").getTime();
      let timeLeft = reminderDate - now;
      setRemainingTime([{
        time: Math.floor(timeLeft / day),
        type: 'days'
      },{
        time: Math.floor((timeLeft % day) / hour),
        type: 'hours'
      },{
        time: Math.floor((timeLeft % hour) / minute),
        type: 'minutes'
      },{
        time: Math.floor((timeLeft % minute) / 1000),
        type: 'seconds'
      }])
  }

  useEffect(() => {
    const interval = setInterval(() => {
      updateRemainingTime();
     
    }, 1000);

    return () => {
      clearInterval(interval);
    };
  }, [remainingTime]);


  return (
    <div className={styles.container}>
      <Head>
        <title>Launch Countdown Timer</title>
        <meta name="description" content="Generated by Mili is my name. Designed by Frontendmentor" />
        <link rel="icon" href="images/favicon-32x32.png" />
        <link href="https://fonts.googleapis.com/css2?family=Red+Hat+Text:wght@700&display=swap" rel="stylesheet" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.subTitle}>
          We&apos;re launching soon
        </h2>
        <div className={styles.grid}>
          {remainingTime.map((item : CardInterface, key: number) => {
                return <Card key={key} time={item.time} type={item.type} />
            })}
        </div>
      </main>
    </div>
  )
}

export default Home
